sopra-fs22-group-36/screw-your-neighbor-server

.github/workflows/documents.yml
.gitignore
doc/m2/FS22-Group-36-M2-Report.md
doc/m2/uml/component_diagram.puml
generate-pdf.sh
render-puml.sh

closes #18 
Example release can be seen here: https://github.com/BacLuc/screw-your-neighbor-server/releases/tag/test-release2

Add ci for puml and pdf and create release on tag

---

doc/latex/options.tex
doc/m2/FS22-Group-36-M2-Report.md
generate-pdf.sh

FS22-Group-36-M2-Report.md: add REST specification

---

doc/m2/FS22-Group-36-M2-Report.md
doc/m2/uml/class_diagram.puml
doc/m2/uml/component_diagram.puml

Apply the changes of @elBeato on the uml branch.
Add some minor modifications.
Remove the components from the class diagram

Depict Rapid Api Development in component diagram

---

src/main/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/entity/Player.java
src/main/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/security/Authorities.java
src/main/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/security/WebSecurityConfig.java
src/main/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/sideeffects/PlayerEventHandler.java
src/main/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/validation/PlayerValidator.java
src/main/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/web/GlobalExceptionHandler.java
src/test/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/api/PlayerIntegrationTest.java
src/test/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/util/SessionUtil.java

Add authentication and minimal authorization

---

doc/m2/uml/activity_requests_diagram.puml
doc/m2/uml/class_diagram.puml

Also add MatchState enum to Match.
#4

doc: add activity diagram with requests

---

doc/latex/options.tex
doc/m2/uml/class_diagram.puml
doc/m2/uml/failing_points/failing_points.md
doc/m2/uml/failing_points/no_reaction_from_player.puml
doc/m2/uml/failing_points/player_leaves_game.puml

Class Diagram in M2 folder updated.

Uml continue

---

src/main/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/security/WebSecurityConfig.java

Else the frontend does not accept responses from the backend on heroku.
Issue: #81

WebSecurityConfig: add protocol to productive cors url

---

src/main/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/entity/Game.java
src/main/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/entity/Player.java
src/main/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/web/GlobalExceptionHandler.java
src/test/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/api/PlayerIntegrationTest.java
src/test/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/entity/GameValidationTest.java
src/test/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/entity/PlayerValidationTest.java

To show how to use bean validation.
Issue: #90

entity: validate Game and Player name length

---

src/main/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/controller/AuthController.java
src/test/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/api/AuthControllerIntegrationTest.java

This fixes the problem that the "me" object hat no _links.self object when refreshing the browser.
Should have written the test at the beginning :(
Issue: #87

Feature add self link in auth controller

---

src/test/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/api/AuthControllerIntegrationTest.java
src/test/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/api/GameIntegrationTest.java
src/test/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/api/PlayerIntegrationTest.java
src/test/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/util/ClearDBAfterTestListener.java

That writing tests is more easy.
Issue: #101

tests: add ClearDBAfterTestListener

---

src/main/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/validation/GameValidator.java
src/main/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/validation/OldStateFetcher.java
src/main/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/validation/ValidationConfig.java
src/test/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/validation/GameValidatorTest.java

Mechanism to was taken from https://stackoverflow.com/questions/25233089/how-to-get-old-entity-value-in-handlebeforesave-event-to-determine-if-a-propert
Issue: #51
Issue: #48

game: validate game state changes

---

src/main/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/validation/GameValidator.java
src/test/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/entity/GameBeanValidationTest.java
src/test/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/entity/PlayerBeanValidationTest.java
src/test/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/validation/GameValidatorTest.java

Follow up to #93.
There I removed the condition, but forgot that now
the problem of https://github.com/sopra-fs22-group-36/screw-your-neighbor-server/pull/93#discussion_r845512901
still remains.
Issue: #51

Bugfix allow changing game name

---

src/main/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/entity/Participation.java
src/test/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/api/GameIntegrationTest.java
src/test/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/api/ParticipationIntegrationTest.java

Participation: set active to true as default

---

src/test/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/H2ConsoleIntegrationTest.java
src/test/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/OpenApiDocsIntegrationTest.java
src/test/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/api/GameIntegrationTest.java
src/test/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/api/ParticipationIntegrationTest.java
src/test/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/api/PlayerIntegrationTest.java
src/test/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/entity/RoundTest.java

tests: remove public class modifiers from junit5 tests

---

src/main/resources/application.properties

Issue: #118
@salwil was right.
It worked on the heroku deployment with https, but not locally.

application.properties: set cookie.secure=true

---

src/main/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/sideeffects/CardEventHandler.java

bugfix duplicate round creation #135, #128

---

doc/m2/uml/class_diagram.puml
src/main/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/entity/Card.java
src/main/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/entity/CardEmbedProjection.java
src/main/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/entity/Hand.java
src/main/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/entity/HandEmbedProjection.java
src/main/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/entity/Participation.java
src/main/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/entity/ParticipationEmbedProjection.java
src/main/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/entity/Round.java
src/main/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/entity/RoundEmbedProjection.java
src/test/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/api/HandIntegrationTest.java
src/test/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/api/ParticipationIntegrationTest.java
src/test/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/api/RoundIntegrationTest.java
src/test/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/entity/CardTest.java
src/test/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/entity/HandScoreTest.java
src/test/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/util/CardValue.java

class_diagram.puml: add methods which are needed to calculate score
refactor/Round: use getHighestCard to calculate trickWinnerIds
Because the getTrickWinnerIds method returns participation ids which we don't want.
Round: add property isStacked
That the frontend can show if the round is stacked.
(When we have implemented the other logic for it).
Card: add property isHighestCardsInRound
That we can highlight the highest cards in
the frontend.
Hand: calculate numberOfWonTricks and points
That we can show the number of won tricks
and the points for a match in the frontend.
Participation: sum up points of hands with getPoints
That we can show the points a player gained in a match.
Issues:
#7
#31 
#61
#68
#131

Feature calculate score

---

src/main/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/repository/MatchRepository.java
src/main/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/sideeffects/HandEventHandler.java
src/test/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/api/HandEventHandlerTest.java

Geht einher mit dem Pull-Request im Frontend. Am besten gleiche Beide - falls einverstanden - mergen. 
#64 Dieser Issue sollte vornehmlich im Frontend abgebarbeitet werden. 
#143

Feature update match state: After all players submit the trick they will made, the MatchState change to "Playing"

---

src/main/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/sideeffects/HandEventHandler.java
src/test/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/api/HandEventHandlerTest.java

Ich hol' das zeugs nicht mehr vom Repo...

simplify the score announcing prozess + add tests with multiply matches

---

src/main/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/entity/Card.java
src/main/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/entity/Hand.java
src/main/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/entity/Match.java
src/main/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/entity/Round.java
src/main/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/repository/PlayerRepository.java
src/main/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/security/expressions/CustomMethodSecurityExpressionRoot.java
src/main/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/serialization/CardEmbedProjectionSerializer.java
src/main/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/serialization/CardSerializer.java
src/main/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/serialization/SerializationConfiguration.java
src/test/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/api/CardApiTest.java
src/test/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/entity/CardTest.java
src/test/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/security/expressions/CustomMethodSecurityExpressionRootTest.java
src/test/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/serialization/CardSerializerTest.java
src/test/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/util/GameBuilder.java

Issue: https://github.com/sopra-fs22-group-36/screw-your-neighbor-server/issues/150

Feature hide card rank and suit if player should not see it

---

build.gradle
src/main/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/entity/Game.java
src/main/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/entity/Player.java
src/main/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/validation/bean/NoHtml.java
src/main/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/validation/bean/NoHtmlValidator.java
src/test/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/api/GameIntegrationTest.java
src/test/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/api/PlayerIntegrationTest.java
src/test/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/entity/GameBeanValidationTest.java
src/test/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/entity/PlayerBeanValidationTest.java

closes https://github.com/sopra-fs22-group-36/screw-your-neighbor-server/issues/166
closes https://github.com/sopra-fs22-group-36/screw-your-neighbor-server/issues/167

Feature secure game and player endpoint

---

src/main/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/entity/Game.java
src/main/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/validation/ParticipationValidator.java
src/test/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/validation/ParticipationValidatorTest.java

Feature validation not more then 5

---

src/main/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/entity/RoundEmbedProjection.java

That the frontend has a self link to identify the card.

RoundEmbedProjection: embed cards with CardEmbedProjection

---

LICENSE.txt
README.md

add license

---

src/main/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/entity/SpringRestConfiguration.java
src/main/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/repository/CardRepository.java
src/main/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/repository/MatchRepository.java
src/main/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/repository/ParticipationRepository.java
src/main/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/repository/RoundRepository.java

Feature protect endpoints

---

src/main/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/entity/Match.java
src/test/java/ch/uzh/ifi/hase/soprafs22/screwyourneighborserver/entity/HandTurnActiveTest.java

Follow the participation numbers ascending instead of descending.
closes #183

Match: rotate the collection correctly
